executable = /srv01/technion/yonlin/scripts/Triangular-J1J2/JobUtilities/RunAFMDispersion.sh
arguments = --Ly $(Ly) --chi_max $(chi_max) --kx $(kx) --ky $(ky) --gs_path $(gs_path)
root_dir = /storage/ph_keselman/yonlin/TriangularJ1J2
case_folder = $(root_dir)/$(case_folder_name)
log_name = run

log = $(case_folder)/$(log_name).log
output = $(case_folder)/$(log_name).out
error = $(case_folder)/$(log_name).err

request_cpus = 10
RequestMemory = (real($(Ly)) * real($(chi_max)) * real($(chi_max)) * 7E-05 + 4) * 1024
Initialdir = $(case_folder)
universe = vanilla
input_file = $(root_dir)/afm_dispersion_condor_cases.txt

queue Ly, chi_max, kx, ky, gs_path, case_folder_name from $(input_file)
